dist: trusty
sudo: required
language: python

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

install:
  - pip install opencv-python pyyaml codecov

cache:
  pip: true

env:
  global:
    - COLUMNS=80

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

script: coverage run --source=mmcv setup.py test

after_success: codecov